# Generated by Django 5.2.7 on 2025-10-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="number",
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="base_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="capacity",
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
