# Generated by Django 5.2.7 on 2025-10-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_alter_room_number_alter_roomtype_base_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomtype",
            name="base_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
