# Generated by Django 5.2.7 on 2025-10-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_alter_roomtype_base_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomtype",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Room type image",
                null=True,
                upload_to="room_types/",
            ),
        ),
    ]
