# Generated by Django 5.2.7 on 2025-10-30 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0004_roomtype_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="roomtype",
            old_name="describtion",
            new_name="description",
        ),
    ]
